### ISSUE TITLE
invalid byte sequence for encoding "UTF8": 0x00 when using Value Converters

### ISSUE THREAD

**Issue by douglasg14b** [yangzhongke/Zack.EFCore.Batch#123]
Full Exception:

> Npgsql.PostgresException (0x80004005): 22021: invalid byte sequence for encoding "UTF8": 0x00
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlBinaryImporter.Complete(Boolean async, CancellationToken cancellationToken)
   at System.Linq.NpgSqlBulkInsertExtensions.BulkInsertAsync[TEntity](DbContext dbCtx, IEnumerable`1 items)
   at Buzzscreens.Features.Seeding.Seeders.EmailDomainsSeeder.Seed() in C:\Users\Douglas\Documents\01 Programming\02 Contracts\buzzscreens-app\apps\backend\Buzzscreens.Features\Seeding\Seeders\EmailDomainsSeeder.cs:line 42
  Exception data:
    Severity: ERROR
    SqlState: 22021
    MessageText: invalid byte sequence for encoding "UTF8": 0x00
    Where: COPY email_domains, line 1, column kind
    File: mbutils.c
    Line: 1665
    Routine: report_invalid_encoding

I'm trying to insert entities with enums that are converted into strings by built in value converters `builder.Property(x => x.Kind).HasConversion<string>();`

EF Core 8

This appears to work fine with normal add/save changes.

**Comment by yangzhongke** [comment]
Thanks for your feedback. Bug fixed. Please upgrade to the latest version.
