### ISSUE TITLE
在生产环境运行半年，突然大量报错

### ISSUE THREAD

**Issue by jinghun1999** [yangzhongke/Zack.EFCore.Batch#137]
找不出任何原因，就是业务部分报错了。对这些数据手工insert却没有任何问题。。。
```
MySqlConnector.MySqlException (0x80004005): 125 rows were copied to XXX but only 0 were inserted.
   at MySqlConnector.MySqlBulkCopy.WriteToServerAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlBulkCopy.cs:line 347
   at MySqlConnector.MySqlBulkCopy.WriteToServerAsync(DataTable dataTable, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlBulkCopy.cs:line 148
   at System.Linq.MySQLBulkInsertExtensions.BulkInsertAsync[TEntity](DbContext dbCtx, IEnumerable`1 items, MySqlTransaction transaction, CancellationToken cancellationToken, Nullable`1 bulkCopyTimeoutInSecond)
   at X.ArchiveService.Bus.Service.ArchiveMATService.ArchiveAccSendSheets(IEntityContext`1 entityContext, IEntityContext`1 detailContext, IConfiguration configuration, Int32 subRow) in /src/src/Archive/X.ArchiveService.Bus/Service/ArchiveMATService.cs:line 443。
```
太惨了

**Comment by yangzhongke** [comment]
根据这个帖子
https://stackoverflow.com/questions/71958383/attempting-to-insert-data-with-mysqlbulkcopy-always-ends-up-with-x-rows-copied

你需要监听MySqlConnection的InfoMessage 事件来了解详细的报错原因：
```
myConnection.InfoMessage += (s, e) =>
{
    // use logging infrastructure of your choice
    foreach (var error in e.Errors)
        Console.WriteLine(error.Message);
};
```
