### ISSUE TITLE
批量新增在实体可空类型中会出错

### ISSUE THREAD

**Issue by wHarbor** [yangzhongke/Zack.EFCore.Batch#16]
测试环境.net 5 + SqlServer
定义实体  public int? id { get; set; } 可空类型
调用BulkInsertAsync 会报错：
System.NotSupportedException: DataSet does not support System.Nullable<>.
   at System.Data.DataColumn..ctor(String columnName, Type dataType, String expr, MappingType type)
   at Zack.EFCore.Batch.Internal.BulkInsertUtils.BuildDataTable[TEntity](DbSet`1 dbSet, IEnumerable`1 items)
   at System.Linq.MSSQLBulkInsertExtensions.BulkInsertAsync[TEntity](DbContext dbCtx, IEnumerable`1 items, CancellationToken cancellationToken)

去掉可空类型后可以批量插入成功！！！

**Comment by yangzhongke** [comment]
谢谢反馈，我会尽快修复

**Comment by yangzhongke** [comment]
已修复，请更新到最新版

**Comment by wHarbor** [comment]
> 已修复，请更新到最新版

好的，谢谢。
