### ISSUE TITLE
引用Mysql如下未找到key值

### ISSUE THREAD

**Issue by SamuelLiDR** [yangzhongke/Zack.EFCore.Batch#17]
项目为abpvnext model的项目，引用如下:
![image](https://user-images.githubusercontent.com/37282255/123197652-68bd5980-d4de-11eb-8b79-dfdef4e7dcbe.png)
错误如下：
System.Collections.Generic.KeyNotFoundException
The given key '__ef_filter__p_0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlParameter(SqlParameterExpression sqlParameterExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveNonNullableColumns, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveNonNullableColumns, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveNonNullableColumns, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Process(SelectExpression selectExpression, IReadOnlyDictionary`2 parameterValues, Boolean& canCache)
   at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlParameterBasedSqlProcessor.ProcessSqlNullability(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.Query.RelationalParameterBasedSqlProcessor.Optimize(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at System.Linq.BatchEFExtensions.Parse[TEntity](IQueryable`1 queryable, DbContext ctx, Boolean ignoreQueryFilters)
   at System.Linq.BatchEFExtensions.GenerateDeleteSQL[TEntity](DbContext ctx, IQueryable`1 queryable, Expression`1 predicate, Boolean ignoreQueryFilters, IReadOnlyDictionary`2& parameters)
   at System.Linq.BatchEFExtensions.DeleteRangeAsync[TEntity](DbContext ctx, Expression`1 predicate, Boolean ignoreQueryFilters, CancellationToken cancellationToken)
   at Dk.OrderSyncApi.PlatformOrder.PlatformOrderInfoRepository.DeleteByNo(String platformOrderNo) in D:\Git\business-center-system\services-module\order-sync-api\src\Dk.OrderSyncApi.EntityFrameworkCore\PlatformOrder\PlatformOrderInfoRepository.cs:line 96
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Dk.OrderSyncApi.EntityFrameworkCore.PlatformOrder.PlatformOrderInfoRepositoryTests.ZackDeleteTest() in D:\Git\business-center-system\services-module\order-sync-api\test\Dk.OrderSyncApi.EntityFrameworkCore.Tests\EntityFrameworkCore\PlatformOrder\PlatformOrderInfoRepositoryTests.cs:line 36
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

**Comment by SamuelLiDR** [comment]
环境为 Abpvnext  .net5 + mysql

**Comment by yangzhongke** [comment]
你调用DeleteRangeAsync的lambda写法，放到数据查询（也就是不是调用我的批量删除的方法，而是写普通的EF Core的查询）的Where()中能够运行正常吗？如果不能的话，那就是Pomelo的Bug，需要把你的Where写法反馈到Pomelo。如果查询的Where不报错，但是DeleteRangeAsync的写法报错，请提供相关代码。

**Comment by SamuelLiDR** [comment]
你好不知道是否下面这张lambda的写法，代码
`var context = await GetDbContextAsync() as OrderSyncApiDbContext;
            if (context != null)
            {
                // 可以执行  并得到数据
                var testList1 = context.Set<PlatformOrderInfo>().Where(x => x.PlatformOrderNo == platformOrderNo).ToListAsync();
                var testList2 = context.PlatformOrderInfos.Where(x => x.PlatformOrderNo == platformOrderNo).ToListAsync();
            }

            // 报错
            var rows = await context.PlatformOrderInfos.DeleteRangeAsync(context, x => x.PlatformOrderNo == platformOrderNo);
            rows = await context.DeleteRangeAsync<PlatformOrderInfo>(x => x.PlatformOrderNo == platformOrderNo);
            return rows > 0;`

**Comment by SamuelLiDR** [comment]
你好不知道是否下面这张lambda的写法，代码
`var context = await GetDbContextAsync() as OrderSyncApiDbContext;
            if (context != null)
            {
                // 可以执行  并得到数据
                var testList1 = context.Set<PlatformOrderInfo>().Where(x => x.PlatformOrderNo == platformOrderNo).ToListAsync();
                var testList2 = context.PlatformOrderInfos.Where(x => x.PlatformOrderNo == platformOrderNo).ToListAsync();
            }

            // 报错
            var rows = await context.PlatformOrderInfos.DeleteRangeAsync(context, x => x.PlatformOrderNo == platformOrderNo);
            rows = await context.DeleteRangeAsync<PlatformOrderInfo>(x => x.PlatformOrderNo == platformOrderNo);
            return rows > 0;`

**Comment by yangzhongke** [comment]
你的代码没有问题。是不是你的实体配置有什么特殊的地方。你方便把一个可执行的、能重现这个问题的最简单的项目发给我吗？发到网盘，粘贴链接到这里就可以。
还有你的mysql是什么版本。

**Comment by SamuelLiDR** [comment]
mysql版本 5.7 
链接：https://pan.baidu.com/s/1Sj9_6TKxG5FPcCd84mn4Pw 
提取码：citx 
查看代码 项目结构： test-->Dk.OrderSyncApi.EntityFrameworkCore.Tests --> PlatformOrderInfoRepositoryTests --> ZackDeleteTest

**Comment by yangzhongke** [comment]
目前可以先通过设置ExecuteAsync、DeleteRangeAsync的ignoreQueryFilters: true参数，禁用QueryFilter，这样的方式绕过。如下：
```
var drowsdf = await context.BatchUpdate<PlatformOrderInfo>()
	.Where(x => x.PlatformOrderNo == platformOrderNo)
	.Set(x => x.State, x => 10)
	.ExecuteAsync(ignoreQueryFilters: true);
```
这样QueryFilter就会被忽略了，如果想继续使用对应的QueryFilter，可以手动把过滤条件写到Where条件中。我下周再研究从根本解决的办法。

**Comment by zhuoyue03007** [comment]
> 目前可以先通过设置ExecuteAsync、DeleteRangeAsync的ignoreQueryFilters: true参数，禁用QueryFilter，这样的方式绕过。如下：
> 
> ```
> var drowsdf = await context.BatchUpdate<PlatformOrderInfo>()
> 	.Where(x => x.PlatformOrderNo == platformOrderNo)
> 	.Set(x => x.State, x => 10)
> 	.ExecuteAsync(ignoreQueryFilters: true);
> ```
> 
> 这样QueryFilter就会被忽略了，如果想继续使用对应的QueryFilter，可以手动把过滤条件写到Where条件中。我下周再研究从根本解决的办法。

组件升级到 6.0.8  你这种写法也会报错  退回到6.0.6就不会

**Comment by chenjingchun** [comment]
> 目前可以先通过设置ExecuteAsync、DeleteRangeAsync的ignoreQueryFilters: true参数，禁用QueryFilter，这样的方式绕过。如下：
> 
> ```
> var drowsdf = await context.BatchUpdate<PlatformOrderInfo>()
> 	.Where(x => x.PlatformOrderNo == platformOrderNo)
> 	.Set(x => x.State, x => 10)
> 	.ExecuteAsync(ignoreQueryFilters: true);
> ```
> 
> 这样QueryFilter就会被忽略了，如果想继续使用对应的QueryFilter，可以手动把过滤条件写到Where条件中。我下周再研究从根本解决的办法。

@yangzhongke 是否已经有解决方案

**Comment by yangzhongke** [comment]
抱歉，对abp不熟，不清楚它是在哪里塞进来的这个过滤条件。
