### ISSUE TITLE
执行批量修改，空指针

### ISSUE THREAD

**Issue by SamuelLiDR** [yangzhongke/Zack.EFCore.Batch#18]
环境 abpvnext  .net5 + mysql 
代码：
```
var context = await GetDbContextAsync() as OrderSyncApiDbContext;
if (context != null)
{
    var drowsdf = await context.BatchUpdate<PlatformOrderInfo>()
        .Where(x => x.PlatformOrderNo == platformOrderNo)
        .Set(x => x.State, x => 10)
        .ExecuteAsync();
}
```
报错：
System.NullReferenceException
Object reference not set to an instance of an object.
   at Zack.EFCore.Batch.Internal.BatchUpdateBuilder`1.Set[TP](Expression`1 name, Expression`1 value)
   at Dk.OrderSyncApi.PlatformOrder.PlatformOrderInfoRepository.DeleteByNo(String platformOrderNo) in D:\Git\business-center-system\services-module\order-sync-api\src\Dk.OrderSyncApi.EntityFrameworkCore\PlatformOrder\PlatformOrderInfoRepository.cs:line 99
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Dk.OrderSyncApi.EntityFrameworkCore.PlatformOrder.PlatformOrderInfoRepositoryTests.ZackDeleteTest() in D:\Git\business-center-system\services-module\order-sync-api\test\Dk.OrderSyncApi.EntityFrameworkCore.Tests\EntityFrameworkCore\PlatformOrder\PlatformOrderInfoRepositoryTests.cs:line 36
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

**Comment by yangzhongke** [comment]
你的代码没有问题。是不是你的实体配置有什么特殊的地方。你方便把一个可执行的、能重现这个问题的最简单的项目发给我吗？发到网盘，粘贴链接到这里就可以。
还有你的mysql是什么版本。

**Comment by SamuelLiDR** [comment]
mysql版本 5.7 
链接：https://pan.baidu.com/s/1Sj9_6TKxG5FPcCd84mn4Pw 
提取码：citx 
查看代码 项目结构： test-->Dk.OrderSyncApi.EntityFrameworkCore.Tests --> PlatformOrderInfoRepositoryTests --> ZackDeleteTest

**Comment by yangzhongke** [comment]
Set要求两个参数的类型完全一致。
因为10是int类型，而State属性是sbyte类型的，所以不一致。
两种方式绕过：
1、把10 显式转换为State属性的sbyte类型：
.Set(x => x.State, x => (sbyte)10)
2、Set显式指定泛型类型
.Set<sbyte>(x => x.State, x => 10)

**Comment by yangzhongke** [comment]
Please make sure the types of name and value are exactly the same. For example, if the type of  property 'State' is sbyte, Set(x => x.State, x => 10) is not correct, please use Set(x => x.State, x => (sbyte)10) or Set<sbyte>(x => x.State, x => 10) instead.

**Comment by SamuelLiDR** [comment]
谢谢 收到，，最后执行ExecuteAsync() 似乎关于问题17就出现了，难道时Pomelo的Bug？
System.Collections.Generic.KeyNotFoundException
The given key '__ef_filter__p_0' was not present in the dictionary.

**Comment by yangzhongke** [comment]
17我还在看。我在不使用Abp的环境中没有重现这个问题。我尝试直接运行你的abp项目试试看吧。
