### ISSUE TITLE
MSSQL 异常

### ISSUE THREAD

**Issue by a83913292** [yangzhongke/Zack.EFCore.Batch#21]
Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.
   at Zack.EFCore.Batch.Internal.BatchUpdateBuilder`1.GenerateSQL(Expression`1 predicate, Boolean ignoreQueryFilters, IReadOnlyDictionary`2& parameters)
   at Zack.EFCore.Batch.Internal.BatchUpdateBuilder`1.ExecuteAsync(Boolean ignoreQueryFilters, CancellationToken cancellationToken)
   at LXD.Demo.Program.Main(String[] args) in D:\MeCode\LXD.Demo\LXD.Demo\Program.cs:line 13
   at LXD.Demo.Program.<Main>(String[] args)

**Comment by yangzhongke** [comment]
你的.NET和EF core分别是什么版本（具体到小版本号）

**Comment by yangzhongke** [comment]
长期未回复的issue，已关闭。
