### ISSUE TITLE
使用杨老师的库之后原有的查询操作无法进行

### ISSUE THREAD

**Issue by chukaif** [yangzhongke/Zack.EFCore.Batch#3]
我用的是SqlServer数据库，加了`options.UseBatchEF();` 之后查询语句后面多了"FETCH FIRST 1 ROWS ONLY"
报错信息如下：

`Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'YQ.EntityFramework.AppDbContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): 在 FETCH 语句中选项 FIRST 的用法无效。
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClientConnectionId:e42047e6-9410-491c-8518-1dec7d2b414d
      Error Number:153,State:2,Class:15
      Microsoft.Data.SqlClient.SqlException (0x80131904): 在 FETCH 语句中选项 FIRST 的用法无效。
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      ClientConnectionId:e42047e6-9410-491c-8518-1dec7d2b414d`

**Comment by yangzhongke** [comment]
请把可以重现你问题的最简化代码传上来。

**Comment by yangzhongke** [comment]
最好传可以可运行的小项目

**Comment by chukaif** [comment]
> 请把可以重现你问题的最简化代码传上来。

好的，这是我基于.net core5.0新建的项目，报错还是一样的
[EfTest.zip](https://github.com/yangzhongke/Zack.EFCore.Batch/files/5741249/EfTest.zip)

**Comment by chukaif** [comment]
![QQ截图20201225140525](https://user-images.githubusercontent.com/50015178/103122210-50e55400-46ba-11eb-8a57-ba3b90ea2a8f.png)
生成的sql如上图，查询单条数据和查询多条数据都是一样的错误，SqlServer不支持 FETCH FIRST 1 ROWS ONLY语句

**Comment by yangzhongke** [comment]
已经找到问题并且想到解决思路，会尽快改好后发布

**Comment by yangzhongke** [comment]
已经解决，请把Nuget包换成Zack.EFCore.Batch.MSSQL，然后把UseBatchEF()改成UseBatchEF_MSSQL()。
如果问题已经修复，请反馈

**Comment by chukaif** [comment]
用了Zack.EFCore.Batch.MSSQL之后可以了，目前没有发现问题
