### ISSUE TITLE
PostgreSql批量插入失败

### ISSUE THREAD

**Issue by aprilyush** [yangzhongke/Zack.EFCore.Batch#70]
版本：Zack.EFCore.Batch.Npgsql/1.5.15
        .NET5 EFCore5 
数据库  PostgreSQL 11.1 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit
```
     22P03: incorrect binary data format£»   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlBinaryImporter.Complete(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlBinaryImporter.Complete()
         at System.Linq.NpgSqlBulkInsertExtensions.BulkInsert[TEntity](DbContext dbCtx, IEnumerable`1 items)
```

**Comment by yangzhongke** [comment]
请提供一个可执行的、能重现这个问题的最简单的项目。发到网盘或者github，然后粘贴链接到这里就可以。
