### ISSUE TITLE
复合主键的实体无法执行批量删除

### ISSUE THREAD

**Issue by fcjmansnake** [yangzhongke/Zack.EFCore.Batch#92]
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: Only entity types with one single primary key are supported.
         at Zack.EFCore.Batch.Internal.BatchUtils.GetPKProperty[TEntity](DbSet`1 dbSet)
         at Zack.EFCore.Batch.Internal.BatchUtils.GetSelectPkExpression[TEntity](DbContext dbCtx)
         at Zack.EFCore.Batch.Internal.BatchUtils.BuildWhereSubQuery[TEntity](IQueryable`1 queryable, DbContext dbCtx, String aliasSeparator)
         at System.Linq.BatchEFExtensions.GenerateDeleteSQL[TEntity](DbContext ctx, IQueryable`1 queryable, Expression`1 predicate, Boolean ignoreQueryFilters, IDictionary`2& parameters)
         at System.Linq.BatchEFExtensions.DeleteRangeAsync[TEntity](DbContext ctx, Expression`1 predicate, Boolean ignoreQueryFilters, CancellationToken cancellationToken)

**Comment by yangzhongke** [comment]
抱歉，我这个库不支持复合主键。
